In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head(8)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
5,258000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...",http://www.sonypictures.com/movies/spider-man3/,559,"[{""id"": 851, ""name"": ""dual identity""}, {""id"": ...",en,Spider-Man 3,The seemingly invincible Spider-Man goes up ag...,115.699814,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-01,890871626,139.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The battle within.,Spider-Man 3,5.9,3576
6,260000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",http://disney.go.com/disneypictures/tangled/,38757,"[{""id"": 1562, ""name"": ""hostage""}, {""id"": 2343,...",en,Tangled,When the kingdom's most wanted-and most charmi...,48.681969,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2010-11-24,591794936,100.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They're taking adventure to new lengths.,Tangled,7.4,3330
7,280000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://marvel.com/movies/movie/193/avengers_ag...,99861,"[{""id"": 8828, ""name"": ""marvel comic""}, {""id"": ...",en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,134.279229,"[{""name"": ""Marvel Studios"", ""id"": 420}, {""name...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2015-04-22,1405403694,141.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Age Has Come.,Avengers: Age of Ultron,7.3,6767

In [4]:
movies=pd.merge(movies,credits)

In [5]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
# genres
# id
# keywords
# language (most of them are English) -->ignore
# title
# overview
# popularity
# cast
# crew
movies = movies[['id','keywords','title','overview','genres','cast','crew']]

In [7]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        4809 non-null   int64
 1   keywords  4809 non-null   object
 2   title     4809 non-null   object
 3   overview  4806 non-null   object
 4   genres    4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 300.6+ KB

In [8]:
movies.head()

,id,keywords,title,overview,genres,cast,crew
0,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [9]:
movies.isnull().sum()#check missing data

id          0
keywords    0
title       0
overview    3
genres      0
cast        0
crew        0
dtype: int64

In [10]:
movies.dropna(inplace=True)#remove missing data

In [19]:
movies.duplicated().sum()

0

In [20]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [21]:
def convert(gen):
    #get the "real" genres helper function
    lis=[]
    for i in ast.literal_eval(gen):
        lis.append(i['name'])
    return lis

In [22]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
)

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [23]:
movies['genres'].apply(convert) #get the genres of all movies

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4806, dtype: object

In [24]:
movies['genres']=movies['genres'].apply(convert)

In [25]:
movies.head()

,id,keywords,title,overview,genres,cast,crew
0,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [26]:
movies['keywords'].apply(convert)

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4804    [united statesâ€“mexico barrier, legs, arms, pap...
4805                                                   []
4806    [date, love at first sight, narration, investi...
4807                                                   []
4808            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4806, dtype: object

In [27]:
movies['keywords']=movies['keywords'].apply(convert)

In [28]:
movies.head()

,id,keywords,title,overview,genres,cast,crew
0,19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [29]:
def con4(gen):
    #get the "real" genres helper function
    lis=[]
    count=0
    for i in ast.literal_eval(gen):
        if count!=4:
            count+=1
            lis.append(i['name'])
        else:
            break
    return lis

In [30]:
movies['cast']=movies['cast'].apply(con4)

In [31]:
movies.head()

,id,keywords,title,overview,genres,cast,crew
0,19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [32]:
def essential(gen):
    #get essential roles in film crew helper function
    lis=[]
   
    for i in ast.literal_eval(gen):
        if i['job']=='Director' or i['job']=='Original Music Composer':
            lis.append(i['name'])
            
    return lis

In [33]:
movies['crew'].apply(essential)

0                  [James Horner, James Cameron]
1                  [Gore Verbinski, Hans Zimmer]
2                    [Thomas Newman, Sam Mendes]
3               [Hans Zimmer, Christopher Nolan]
4                               [Andrew Stanton]
                          ...
4804                          [Robert Rodriguez]
4805                              [Edward Burns]
4806                  [Hal Beckett, Scott Smith]
4807                               [Daniel Hsia]
4808    [Brian Herzlinger, Jon Gunn, Brett Winn]
Name: crew, Length: 4806, dtype: object

In [34]:
movies['crew']= movies['crew'].apply(essential)

In [35]:
movies.head()

,id,keywords,title,overview,genres,cast,crew
0,19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[James Horner, James Cameron]"
1,285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[Gore Verbinski, Hans Zimmer]"
2,206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...","[Thomas Newman, Sam Mendes]"
3,49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[Christian Bale, Michael Caine, Gary Oldman, A...","[Hans Zimmer, Christopher Nolan]"
4,49529,"[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [36]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [37]:
movies.head()

,id,keywords,title,overview,genres,cast,crew
0,19995,"[culture clash, future, space war, space colon...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[James Horner, James Cameron]"
1,285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[Gore Verbinski, Hans Zimmer]"
2,206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...","[Thomas Newman, Sam Mendes]"
3,49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[Christian Bale, Michael Caine, Gary Oldman, A...","[Hans Zimmer, Christopher Nolan]"
4,49529,"[based on novel, mars, medallion, space travel...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [38]:
#eliminate space
movies['genres']=movies['genres'].apply(lambda x: [i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x: [i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x: [i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x: [i.replace(" ","") for i in x])

In [39]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [40]:
movies.head()

,id,keywords,title,overview,genres,cast,crew,tags
0,19995,"[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...","[JamesHorner, JamesCameron]","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,"[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...","[GoreVerbinski, HansZimmer]","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...","[ThomasNewman, SamMendes]","[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,"[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[ChristianBale, MichaelCaine, GaryOldman, Anne...","[HansZimmer, ChristopherNolan]","[Following, the, death, of, District, Attorney..."
4,49529,"[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [41]:
#define new dataframe
new_df=movies[['id','title','tags']]

In [42]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

<ipython-input-42-53a061086f2e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [43]:
new_df.head()

,id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [44]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver StephenLang JamesHorner JamesCameron'

In [45]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

<ipython-input-45-242d679aab18>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [46]:
new_df.head()

,id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [47]:
import nltk

In [48]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [49]:
#helper function: to get the stem word. ex. loves->love 
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [50]:
new_df['tags']=new_df['tags'].apply(stem)

<ipython-input-50-402dd7cb6b10>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [51]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [52]:
v=cv.fit_transform(new_df['tags']).toarray()

In [53]:
v

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [54]:
v[0]

array([0, 0, 0, ..., 0, 0, 0])

In [56]:
from sklearn.metrics.pairwise import cosine_similarity

In [60]:
similarity=cosine_similarity(v)

In [70]:
#main function
def recommend(movie):
    movie_index=new_df[new_df['title']==movie].index[0] #id
    dist=similarity[movie_index]
    rec_movies=sorted(list(enumerate(dist)),reverse=True,key=lambda x:x[1])[1:7]
    for i in rec_movies:
        print(new_df.iloc[i[0]].title)

In [61]:
sorted(similarity[0],reverse=True)

[1.0000000000000002,
 0.2833152987899314,
 0.2811237422961876,
 0.25231028011870793,
 0.2506402059138015,
 0.24194822861802104,
 0.2401922307076307,
 0.24019223070763068,
 0.2335709179335258,
 0.22880215766121476,
 0.22645540682891918,
 0.22237479499833035,
 0.2204155075111935,
 0.21982600255746473,
 0.21982600255746473,
 0.20483662259967567,
 0.20180183819889372,
 0.20174251088960077,
 0.20174251088960074,
 0.20131905799006777,
 0.20073126386549828,
 0.20033416898825335,
 0.20006252931214213,
 0.19814848097530424,
 0.19795764159656265,
 0.19611613513818407,
 0.19512313566832118,
 0.19512313566832118,
 0.19312181983410703,
 0.1913897505877382,
 0.1887128390240993,
 0.18685673434682065,
 0.1860521018838127,
 0.18490006540840973,
 0.1849000654084097,
 0.1849000654084097,
 0.1849000654084097,
 0.18302666282596894,
 0.17948717948717946,
 0.17937941173234997,
 0.17841031003501576,
 0.17841031003501576,
 0.1754116038614058,
 0.17471413945365305,
 0.17295817388759027,
 0.17255919256291524,
 0.17093520167692652,
 0.17093520167692652,
 0.1709352016769265,
 0.1709352016769265,
 0.1706971854997297,
 0.16984155512168933,
 0.16898159235484367,
 0.16724840200141816,
 0.16724840200141816,
 0.167093470609201,
 0.1667752796900333,
 0.16477051091432687,
 0.16349964255346808,
 0.1634301126151534,
 0.16269036695641684,
 0.16239958858823,
 0.1617875572323585,
 0.1611258466588724,
 0.16012815380508716,
 0.1601281538050871,
 0.1585187847802434,
 0.15695698526580623,
 0.15631503171567185,
 0.15585730003983933,
 0.15534712747612348,
 0.15408338784034142,
 0.15408338784034142,
 0.15097027121927944,
 0.1500468969841066,
 0.1500468969841066,
 0.148916158209988,
 0.14824986333222023,
 0.147180996735913,
 0.1465158871516513,
 0.14617633655117152,
 0.14484136487558028,
 0.14484136487558028,
 0.14484136487558028,
 0.14412659875498,
 0.1437993271357627,
 0.1437993271357627,
 0.1432229748078866,
 0.14322297480788657,
 0.14235407108686474,
 0.1416576493949657,
 0.1416576493949657,
 0.14153462926807447,
 0.1401425507601155,
 0.1401425507601155,
 0.14011213457945124,
 0.13977131156292244,
 0.13977131156292244,
 0.13977131156292244,
 0.13937366833451514,
 0.13937366833451514,
 0.13937366833451514,
 0.1386750490563073,
 0.1373087590952724,
 0.1373087590952724,
 0.1373087590952724,
 0.1373087590952724,
 0.13725270326150324,
 0.13725270326150324,
 0.13693937303317935,
 0.13693937303317935,
 0.13655774839978377,
 0.13655774839978377,
 0.13655774839978377,
 0.13655774839978377,
 0.1358732440973515,
 0.13533299049019168,
 0.13533299049019168,
 0.13533299049019168,
 0.13355611265883557,
 0.13355611265883557,
 0.13344012817090595,
 0.13323467750529824,
 0.13323467750529824,
 0.1320989873168695,
 0.1319717610643751,
 0.1319717610643751,
 0.1316245316231641,
 0.1316245316231641,
 0.1316245316231641,
 0.1316245316231641,
 0.1307440900921227,
 0.1307440900921227,
 0.1307440900921227,
 0.13074409009212268,
 0.12955005512625914,
 0.1283881477532739,
 0.1282051282051282,
 0.1282051282051282,
 0.1282051282051282,
 0.12810252304406972,
 0.12810252304406972,
 0.12810252304406972,
 0.12810252304406972,
 0.12810252304406972,
 0.12659242088545833,
 0.12659242088545833,
 0.12659242088545833,
 0.12659242088545833,
 0.12659242088545833,
 0.12659242088545833,
 0.12561485860426555,
 0.12561485860426555,
 0.12561485860426555,
 0.12561485860426555,
 0.12503908082008883,
 0.12503908082008883,
 0.1235415527768502,
 0.12326671027227314,
 0.12326671027227314,
 0.12326671027227314,
 0.12301385521570944,
 0.1220965726263761,
 0.12209657262637608,
 0.12209657262637608,
 0.12201777521731262,
 0.12104550653376048,
 0.12104550653376048,
 0.12104550653376048,
 0.12104550653376048,
 0.12104550653376048,
 0.12104550653376046,
 0.1207011373963169,
 0.1207011373963169,
 0.12009611535381536,
 0.12009611535381536,
 0.12009611535381534,
 0.12009611535381534,
 0.12009611535381534,
 0.12009611535381534,
 0.12009611535381534,
 0.11935247900657214,
 0.11935247900657214,
 0.11935247900657214,
 0.11894020669001051,
 0.11894020669001051,
 0.11894020669001051,
 0.1180480411624714,
 0.11737660545701087,
 0.11737660545701087,
 0.11694106924093722,
 0.11694106924093722,
 0.11694106924093722,
 0.11694106924093722,
 0.11694106924093722,
 0.11694106924093722,
 0.11678545896676293,
 0.11651034560709261,
 0.11651034560709261,
 0.11651034560709261,
 0.1165103456070926,
 0.11556254088025608,
 0.11556254088025608,
 0.11556254088025608,
 0.11503946170861017,
 0.11503946170861017,
 0.11503946170861017,
 0.11437725271791938,
 0.11437725271791938,
 0.11437725271791938,
 0.11437725271791938,
 0.114022293537793,
 0.1139331787969125,
 0.1138098548271451,
 0.11322770341445958,
 0.11322770341445958,
 0.11322770341445956,
 0.11265439490322912,
 0.11244949691847503,
 0.11211213233271873,
 0.11211213233271873,
 0.11149893466761211,
 0.11102889792108188,
 0.11102889792108186,
 0.11098534863604863,
 0.11094003924504582,
 0.11020775375559674,
 0.11020775375559674,
 0.11020775375559674,
 0.11020775375559674,
 0.11020775375559674,
 0.10997646755364593,
 0.10984700727621793,
 0.10984700727621793,
 0.10984700727621793,
 0.10948978029027179,
 0.10948978029027179,
 0.10895340841010223,
 0.10895340841010223,
 0.10895340841010223,
 0.10878565864408421,
 0.10826639239215334,
 0.10826639239215334,
 0.10826639239215334,
 0.10826639239215334,
 0.10826639239215334,
 0.10826639239215334,
 0.10826639239215334,
 0.10826639239215334,
 0.10826639239215334,
 0.108094949066235,
 0.10741723110591492,
 0.10699012312772824,
 0.10699012312772824,
 0.10699012312772824,
 0.10675210253672475,
 0.10675210253672475,
 0.10675210253672475,
 0.10675210253672475,
 0.10675210253672475,
 0.10675210253672475,
 0.10639084227042908,
 0.10604746049596296,
 0.10604746049596296,
 0.10604746049596295,
 0.10529962529853128,
 0.10529962529853128,
 0.10529962529853128,
 0.105129283382795,
 0.10482848367219183,
 0.10482848367219183,
 0.10482848367219183,
 0.10482848367219183,
 0.10482848367219183,
 0.10423454980627081,
 0.10390486669322622,
 0.10390486669322622,
 0.10390486669322622,
 0.10390486669322622,
 0.10336227882434038,
 0.10336227882434038,
 0.10336227882434038,
 0.10256410256410256,
 0.10256410256410256,
 0.10256410256410256,
 0.10256410256410256,
 0.1025115460130912,
 0.1025115460130912,
 0.10241831129983783,
 0.10241831129983783,
 0.10241831129983783,
 0.10241831129983783,
 0.10241831129983783,
 0.10241831129983783,
 0.10241831129983783,
 0.10241831129983782,
 0.10168147934776052,
 0.10168147934776052,
 0.10168147934776052,
 0.10127393670836667,
 0.10127393670836667,
 0.10127393670836667,
 0.10127393670836667,
 0.10127393670836667,
 0.10016708449412667,
 0.10016708449412667,
 0.10016708449412667,
 0.10016708449412667,
 0.10016708449412667,
 0.10016708449412667,
 0.10016708449412667,
 0.10016708449412667,
 0.10016708449412667,
 0.10016708449412667,
 0.10016708449412667,
 0.10016708449412667,
 0.10008009612817946,
 0.10008009612817946,
 0.10008009612817945,
 0.10003126465607107,
 0.10003126465607107,
 0.10003126465607107,
 0.10003126465607107,
 0.09883324222148016,
 0.09883324222148016,
 0.09883324222148016,
 0.09883324222148016,
 0.09883324222148016,
 0.09805806756909202,
 0.09805806756909202,
 0.09805806756909202,
 0.09805806756909202,
 0.09805806756909202,
 0.09805806756909202,
 0.09805806756909202,
 0.09805806756909202,
 0.09781383788084239,
 0.09781383788084239,
 0.09767725810110087,
 0.09767725810110087,
 0.09767725810110087,
 0.09767725810110087,
 0.09767725810110087,
 0.09767725810110087,
 0.09709195467257717,
 0.09656090991705352,
 0.09656090991705352,
 0.09656090991705352,
 0.09656090991705352,
 0.09607689228305229,
 0.09607689228305229,
 0.09607689228305229,
 0.09607689228305229,
 0.09607689228305229,
 0.09607689228305229,
 0.0956948752938691,
 0.09548198320525772,
 0.09548198320525772,
 0.09548198320525772,
 0.09548198320525772,
 0.09548198320525772,
 0.09548198320525772,
 0.09548198320525772,
 0.09443843292997713,
 0.09443843292997713,
 0.09443843292997713,
 0.09443843292997713,
 0.09443843292997713,
 0.09435641951204965,
 0.09421114395319916,
 0.09421114395319916,
 0.09421114395319916,
 0.09421114395319916,
 0.09421114395319916,
 0.09421114395319916,
 0.09421114395319916,
 0.09421114395319916,
 0.09421114395319916,
 0.09421114395319916,
 0.09342836717341035,
 0.09342836717341034,
 0.09342836717341034,
 0.09342836717341034,
 0.09342836717341034,
 0.09342836717341034,
 0.0930725988812425,
 0.0930725988812425,
 0.09245003270420486,
 0.09245003270420486,
 0.09245003270420486,
 0.09245003270420486,
 0.09245003270420485,
 0.09245003270420485,
 0.09245003270420485,
 0.09245003270420485,
 0.09245003270420485,
 0.09245003270420485,
 0.09245003270420485,
 0.09245003270420485,
 0.09245003270420485,
 0.0915018021743355,
 0.0915018021743355,
 0.0915018021743355,
 0.0915018021743355,
 0.0915018021743355,
 0.0915018021743355,
 0.0915018021743355,
 0.09078412990032037,
 0.09078412990032037,
 0.09078412990032037,
 0.09078412990032037,
 0.09078412990032037,
 0.09078412990032037,
 0.09078412990032037,
 0.09065471553673685,
 0.09058216273156766,
 0.09058216273156766,
 0.09058216273156766,
 0.09007912422186248,
 0.08968970586617499,
 0.08968970586617499,
 0.08968970586617499,
 0.08968970586617499,
 0.08968970586617499,
 0.08968970586617499,
 0.08951435925492911,
 0.08920515501750789,
 0.08920515501750789,
 0.08920515501750789,
 0.08920515501750789,
 0.08920515501750789,
 0.08920515501750789,
 0.08920515501750789,
 0.08920515501750789,
 0.0888231183368655,
 0.0888231183368655,
 0.0888231183368655,
 0.0888231183368655,
 0.0888231183368655,
 0.0888231183368655,
 0.0888231183368655,
 0.0888231183368655,
 0.0888231183368655,
 0.08806599154457967,
 0.08798117404291673,
 0.08798117404291673,
 0.08798117404291673,
 0.08798117404291673,
 0.08788174152965353,
 0.08770580193070292,
 0.08770580193070292,
 0.08770580193070292,
 0.08770580193070292,
 0.08770580193070292,
 0.08770580193070292,
 0.08770580193070292,
 0.08770580193070292,
 0.08770580193070292,
 0.08735706972682653,
 0.08716272672808179,
 0.08716272672808179,
 0.08716272672808179,
 0.08684168428648435,
 0.0863667034175061,
 0.08627959628145762,
 0.08627959628145762,
 0.08627959628145762,
 0.08627959628145762,
 0.08627959628145762,
 0.08627959628145762,
 0.08559209850218259,
 0.08559209850218259,
 0.08559209850218259,
 0.08559209850218259,
 0.08559209850218259,
 0.08559209850218259,
 0.08559209850218259,
 0.08559209850218259,
 0.08559209850218259,
 0.08559209850218259,
 0.08492077756084468,
 0.08492077756084468,
 0.08492077756084468,
 0.08492077756084468,
 0.08492077756084468,
 0.08492077756084468,
 0.08492077756084468,
 0.08492077756084468,
 0.08492077756084468,
 0.08492077756084468,
 0.08492077756084468,
 0.08483796839677037,
 0.08483796839677037,
 0.08483796839677037,
 0.08483796839677037,
 0.08483796839677037,
 0.084103426706236,
 0.084103426706236,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070907,
 0.08338763984501665,
 0.0826898230594723,
 0.0826898230594723,
 0.0826898230594723,
 0.0826898230594723,
 0.0826898230594723,
 0.0826898230594723,
 0.0826898230594723,
 0.0826898230594723,
 0.0826898230594723,
 0.0826898230594723,
 0.0826898230594723,
 0.0826898230594723,
 0.08238525545716345,
 0.08238525545716345,
 0.08238525545716345,
 0.08238525545716345,
 0.08238525545716345,
 0.08238525545716345,
 0.08200923681047297,
 0.08200923681047297,
 0.08134518347820842,
 0.08134518347820842,
 0.08129275344796079,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.081199794294115,
 0.0806970043558403,
 0.0806970043558403,
 0.0806970043558403,
 0.0806970043558403,
 0.08006407690254357,
 0.08006407690254357,
 0.08006407690254357,
 0.08006407690254357,
 0.08006407690254357,
 0.08006407690254357,
 0.08006407690254357,
 0.08006407690254357,
 0.08006407690254357,
 0.08006407690254357,
 0.08006407690254357,
 0.08006407690254357,
 0.08006407690254357,
 0.08006407690254357,
 0.08006407690254357,
 0.08006407690254357,
 0.08006407690254357,
 0.08006407690254357,
 0.08006407690254357,
 0.07944581222989573,
 0.07944581222989573,
 0.07944581222989573,
 0.07944581222989573,
 0.07897471897389846,
 0.07897471897389846,
 0.07897471897389846,
 0.07897471897389846,
 0.07897471897389846,
 0.07897471897389846,
 0.07897471897389846,
 0.07897471897389846,
 0.07897471897389846,
 0.07897471897389846,
 0.07888947910127372,
 0.07884165279854434,
 0.07884165279854434,
 0.0782510703046739,
 0.0782510703046739,
 0.0782510703046739,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07792865001991967,
 0.07776510597812535,
 0.07767356373806174,
 0.07767356373806174,
 0.07767356373806174,
 0.07767356373806174,
 0.07767356373806174,
 0.07767356373806174,
 0.07767356373806174,
 0.07692307692307693,
 0.07692307692307693,
 0.07692307692307693,
 0.07692307692307693,
 0.07655590023509527,
 0.07655590023509527,
 0.07655590023509527,
 0.07601486235852867,
 0.07601486235852867,
 0.075955452531275,
 0.075955452531275,
 0.075955452531275,
 0.075955452531275,
 0.075955452531275,
 0.075955452531275,
 0.075955452531275,
 0.075955452531275,
 0.075955452531275,
 0.075955452531275,
 0.07548513560963972,
 0.07548513560963972,
 0.07548513560963972,
 0.07548513560963972,
 0.07548513560963972,
 0.07548513560963972,
 0.07548513560963972,
 0.07548513560963972,
 0.07548513560963972,
 0.07502344849205331,
 0.07502344849205331,
 0.07502344849205331,
 0.07502344849205331,
 0.07502344849205331,
 0.07502344849205331,
 0.07502344849205331,
 0.07502344849205331,
 0.07502344849205331,
 0.07502344849205331,
 0.07496633127898335,
 0.07496633127898335,
 0.07466013667894413,
 0.07457013045372174,
 0.074458079104994,
 0.07412493166611012,
 0.07412493166611012,
 0.07412493166611012,
 0.07412493166611012,
 0.07412493166611012,
 0.07412493166611012,
 0.07412493166611012,
 0.07412493166611012,
 0.07412493166611012,
 0.07412493166611012,
 0.07412493166611012,
 0.07412493166611012,
 0.07412493166611012,
 0.07412493166611012,
 0.07396002616336388,
 0.0734718358370645,
 0.0734718358370645,
 0.0734718358370645,
 0.0734718358370645,
 0.0734718358370645,
 0.0734718358370645,
 0.0734718358370645,
 0.0734718358370645,
 0.0734718358370645,
 0.0734718358370645,
 0.0734718358370645,
 0.0734718358370645,
 0.0734718358370645,
 0.0734718358370645,
 0.0734718358370645,
 0.07325794357582566,
 0.07325794357582566,
 0.07325794357582566,
 0.07325794357582566,
 0.07325794357582566,
 0.07325794357582566,
 0.07325794357582566,
 0.07325794357582566,
 0.07299318686018119,
 0.07299318686018119,
 0.07299318686018119,
 0.07252377242938948,
 0.07242068243779014,
 0.07242068243779014,
 0.07242068243779014,
 0.07242068243779014,
 0.07242068243779014,
 0.07242068243779014,
 0.07242068243779014,
 0.07242068243779014,
 0.07242068243779014,
 0.07206329937749,
 0.0716114874039433,
 0.0716114874039433,
 0.0716114874039433,
 0.0716114874039433,
 0.0716114874039433,
 0.0716114874039433,
 0.0716114874039433,
 0.07161148740394328,
 0.07161148740394328,
 0.07161148740394328,
 0.07161148740394328,
 0.07161148740394328,
 0.07161148740394328,
 0.07161148740394328,
 0.07161148740394328,
 0.07161148740394328,
 0.07161148740394328,
 0.07161148740394328,
 0.07161148740394328,
 0.07161148740394328,
 0.07161148740394328,
 0.07161148740394328,
 0.07161148740394328,
 0.07161148740394328,
 0.07132674875181882,
 0.0711680683578165,
 0.07082882469748285,
 0.07082882469748285,
 0.07082882469748285,
 0.07082882469748285,
 0.07082882469748285,
 0.07082882469748285,
 0.07082882469748285,
 0.07082882469748285,
 0.07082882469748285,
 0.07082882469748285,
 0.07073278556897407,
 0.07073278556897407,
 0.07007127538005775,
 0.07007127538005775,
 0.07007127538005775,
 0.07007127538005775,
 0.07007127538005775,
 0.07007127538005775,
 0.07007127538005775,
 0.07007127538005775,
 0.07007127538005775,
 0.06988565578146122,
 0.06988565578146122,
 0.06988565578146122,
 0.06988565578146122,
 0.06988565578146122,
 0.06988565578146122,
 0.06988565578146122,
 0.06988565578146122,
 0.06988565578146122,
 0.06988565578146122,
 0.06988565578146122,
 0.06988565578146122,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06862635163075162,
 0.06862635163075162,
 0.06862635163075162,
 0.06862635163075162,
 0.06862635163075162,
 0.06862635163075162,
 0.06862635163075162,
 0.06862635163075162,
 0.06827887419989188,
 0.06827887419989188,
 0.06827887419989188,
 0.06827887419989188,
 0.06827887419989188,
 0.06827887419989188,
 0.06827887419989188,
 0.06827887419989188,
 0.06793662204867575,
 0.06793662204867575,
 0.06793662204867575,
 0.06793662204867575,
 0.06793662204867575,
 0.06793662204867575,
 0.06793662204867575,
 0.06793662204867575,
 0.06793662204867575,
 0.06751595780557777,
 0.06726727939963124,
 0.06726727939963124,
 0.06726727939963124,
 0.06726727939963124,
 0.06726727939963124,
 0.06726727939963124,
 0.06726727939963124,
 0.06726727939963124,
 0.06677805632941779,
 0.06677805632941779,
 0.06677805632941779,
 0.06677805632941779,
 0.06677805632941779,
 0.06677805632941779,
 0.06677805632941779,
 0.06677805632941779,
 0.06677805632941779,
 0.06677805632941779,
 0.06661733875264912,
 0.06661733875264912,
 0.06661733875264912,
 0.06661733875264912,
 0.06661733875264912,
 0.06661733875264912,
 0.06641806418489572,
 0.06598588053218755,
 0.06598588053218755,
 0.06598588053218755,
 0.06598588053218755,
 0.06598588053218755,
 0.06598588053218755,
 0.06598588053218755,
 0.06571520774535256,
 0.06537204504606135,
 0.06537204504606135,
 0.06537204504606135,
 0.06537204504606135,
 0.06537204504606135,
 0.06537204504606135,
 0.06537204504606135,
 0.06537204504606135,
 0.06537204504606135,
 0.06537204504606135,
 0.06537204504606135,
 0.06537204504606135,
 0.06537204504606135,
 0.06537204504606135,
 0.06537204504606135,
 0.06537204504606135,
 0.06537204504606135,
 0.06537204504606135,
 0.06537204504606135,
 0.06537204504606135,
 0.06537204504606134,
 0.06537204504606134,
 0.06537204504606134,
 0.06537204504606134,
 0.06503420275836863,
 0.06494054168326639,
 0.06477502756312958,
 0.06477502756312958,
 0.06477502756312958,
 0.06477502756312958,
 0.06477502756312958,
 0.06477502756312958,
 0.06477502756312958,
 0.06477502756312958,
 0.06477502756312958,
 0.06437393994470235,
 0.06419407387663695,
 0.06419407387663695,
 0.06419407387663695,
 0.06419407387663695,
 0.06419407387663695,
 0.06419407387663695,
 0.06419407387663695,
 0.06419407387663693,
 0.06405126152203486,
 0.06405126152203486,
 0.06405126152203486,
 0.06405126152203486,
 0.06405126152203486,
 0.06405126152203486,
 0.06405126152203486,
 0.06405126152203486,
 0.06405126152203486,
 0.06405126152203486,
 0.06405126152203486,
 0.06405126152203486,
 0.06405126152203486,
 0.06405126152203486,
 0.06405126152203486,
 0.06405126152203486,
 0.06405126152203486,
 0.06405126152203486,
 0.06405126152203486,
 0.06405126152203486,
 0.06362847629757777,
 0.06362847629757777,
 0.06362847629757777,
 0.06362847629757777,
 0.063077570029677,
 0.063077570029677,
 0.063077570029677,
 0.063077570029677,
 0.063077570029677,
 0.063077570029677,
 0.063077570029677,
 0.06280742930213278,
 0.06280742930213278,
 0.06280742930213278,
 0.06280742930213278,
 0.06280742930213278,
 0.06280742930213278,
 0.06280742930213278,
 0.06280742930213278,
 0.06280742930213278,
 0.06280742930213278,
 0.06280742930213278,
 0.06280742930213278,
 0.06280742930213278,
 0.06280742930213278,
 0.06280742930213278,

In [73]:
recommend('Batman')

Batman
Batman & Robin
Batman Returns
Batman Begins
The R.M.
The Dark Knight Rises

In [67]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:7]

[(2409, 0.2833152987899314),
 (1216, 0.2811237422961876),
 (507, 0.25231028011870793),
 (3730, 0.2506402059138015),
 (582, 0.24194822861802104),
 (1444, 0.2401922307076307)]

In [74]:
import pickle

In [75]:
pickle.dump(new_df,open('movies.pkl','wb'))